trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureStaticWebApp@0
  inputs:
    skip_app_build: true
    skip_api_build: true
    azure_static_web_apps_api_token: '$(DeploymentToken)'
